### ISSUE TITLE
If you are not located at the root of the repository, WStrip strips the entire file

### ISSUE THREAD

**Issue by davidmi** [tweekmonster/wstrip.vim#1]
If you are in a subdirectory of the the git repository, and open a file via it's relative path, :WStrip strips the entire file instead of only the changed lines.

**Comment by tweekmonster** [comment]
Could you clarify this:

> open a file via it's relative path

or give an example?

**Comment by tweekmonster** [comment]
@davidmi does #3 resolve this issue?

**Comment by davidmi** [comment]
#3 does not resolve.
To reproduce:
Create a new git repository
mkdir foo
edit foo/bar and add lines with trailing whitespace
git commit
edit foo/bar and run :WStrip -- nothing is changed, as expected
cd foo
edit bar
run :WStrip
The trailing whitespace is removed even though the line is unchanged.

**Comment by tweekmonster** [comment]
@davidmi Could you give #4 a try?

**Comment by davidmi** [comment]
Seems to work!

**Comment by davidmi** [comment]
Thank you!
