### ISSUE TITLE
Don't store temporarily files in the current directory, store them in a temporary folder instead (currently breaks live reload servers)

### ISSUE THREAD

**Issue by dylan-chong** [tweekmonster/wstrip.vim#7]
This plug-in, as far as I'm aware, stores a temporary file in the same directory as the file being edited. The creation and deletion of this file causes some problems with live reload servers as the creation and deletion of this file triggers extra reloads, and seems to sometimes cause crashes (I think this is when the file is quickly created and then deleted, exposing a race condition in the live reload server). (It took me a very long time to figure out that it was this plug-in, causing the above issues).

It would be better if the temporary files were stored in the temporary directory, or at some other location, so do not interfere with tools that watch changes to all files in the current directory.

**Comment by dylan-chong** [comment]
@tweekmonster Is this plugin still alive? It would be a shame if this plugin were to die as this is a probably the best whitespace stripping plugin out there that i can find!

**Comment by tweekmonster** [comment]
@dylan-chong Sorry, still alive.  But, I was on a long hiatus.

I believe the reason I created a new file next to the original was that `git diff` didn't like making comparisons to files outside the work tree.  Part of the reason I thought this was fine was because Vim created a temporary file in the same directory as the current file for atomic writes.

Could the issue be more to do with the temporary files having the same file extension as the file being compared?

> It would be a shame if this plugin were to die as this is a probably the best whitespace stripping plugin out there that i can find!

Thanks 😭

**Comment by dylan-chong** [comment]
Sorry, didn't realise there was a question in your comment last year!

> Could the issue be more to do with the temporary files having the same file extension as the file being compared?

That could be part of the issue. Creating and deleting this extra file would still trigger live reloads twice extra which is not a good idea

> I believe the reason I created a new file next to the original was that git diff didn't like making comparisons to files outside the work tree. Part of the reason I thought this was fine was because Vim created a temporary file in the same directory as the current file for atomic writes.

Looks like the solution could be pretty easy

https://stackoverflow.com/a/17194704

**Comment by tweekmonster** [comment]
@dylan-chong No sweat, I didn't follow up either 😬

In addition to triggering live reloads, this makes editing files in read-only directories annoying.  I found a workaround for comparing against git objects that should resolve this issue for you.  Let me know if something else comes up!

**Comment by dylan-chong** [comment]
@tweekmonster Thanks so much for implementing this!
